'use strict';
(() => {
 const D=window.WORKSHOP, $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
 const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const PREFIX='naivasha-2026-';
 function read(key,fallback){try{return JSON.parse(localStorage.getItem(PREFIX+key))??fallback;}catch{return fallback;}}
 function write(key,value){try{localStorage.setItem(PREFIX+key,JSON.stringify(value));return true;}catch{toast('This browser cannot save locally. Export your notes before leaving.');return false;}}
 let completed=read('completed',[]), notes=read('notes',{}), game=read('game',{current:0,rounds:{},team:'',reflection:''}), roleConfirmed=false;
 if(!Array.isArray(completed))completed=[];
 if(!notes||typeof notes!=='object'||Array.isArray(notes))notes={};
 if(!game||typeof game!=='object'||!game.rounds||typeof game.rounds!=='object')game={current:0,rounds:{},team:'',reflection:''};
 game.current=Math.max(0,Math.min(5,Math.trunc(Number(game.current))||0));
 let currentRoute='',currentParams=new URLSearchParams(),timer=null,openingIndex=0,launchIncluded=false,blank=false,gameHelp=false,lastDealtRound=null;
 const main=$('#main');
 const navLink=(route,text,cls='button secondary')=>`<a class="${cls}" href="#${route}">${text}</a>`;
 const download=(file,text='Download PDF',cls='button small')=>`<a class="${cls}" href="${esc(file)}" download>${text} <span aria-hidden="true">↓</span></a>`;
 const dayTabs=(selected,handler,all=false)=>`<div class="tabs" aria-label="Workshop days">${all?`<button data-${handler}="0" aria-pressed="${selected===0}">All days</button>`:''}${D.days.map(d=>`<button data-${handler}="${d.number}" aria-pressed="${selected===d.number}">${d.weekday.slice(0,3)} ${d.number+11} Oct</button>`).join('')}</div>`;
 function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),4000);}
 function exportText(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function go(route,params={}){const q=new URLSearchParams(params).toString();location.hash=route+(q?'?'+q:'');}
 function paramNumber(name,max,fallback=0){const n=Number(currentParams.get(name));return Number.isInteger(n)&&n>=0&&n<=max?n:fallback;}
 function header(eyebrow,title,desc){return `<div class="page-head"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div>`;}
 function render(){
  const raw=location.hash.slice(1)||'home', split=raw.split('?');currentRoute=split[0];currentParams=new URLSearchParams(split.slice(1).join('?'));
  const routes={home,programme,opening,activities,standards,lab,notebook};if(!routes[currentRoute]){currentRoute='home';}
  document.body.classList.toggle('game-playing',currentRoute==='lab'&&gameMode()!=='');
  if(timer){clearInterval(timer);timer=null;}
  main.innerHTML=routes[currentRoute]();
  $$('nav a').forEach(a=>{const active=a.dataset.route===currentRoute;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  document.title=({home:'Welcome',programme:'The week',opening:'Opening session',activities:'Activity desk',standards:'Standards & law',lab:'Agreement Lab',notebook:'My notebook'}[currentRoute])+' · Naivasha 2026';
  if(currentRoute==='notebook')calculate();
  if(currentRoute==='lab'&&gameMode())startTimerDisplay();
 }
 function home(){return `
  <section class="hero"><div class="eyebrow">Naivasha · 12–16 October 2026</div><h1>Shared purpose.<br>Stronger negotiation.</h1><p>Social dialogue in Kenya’s public health and higher education sectors. A week to connect, prepare, practise and take useful skills back to work.</p><div class="actions">${navLink('programme','Explore the week →','button gold')}${navLink('opening','Open the opening session','button secondary')}</div><div class="hero-stamp"><span>Two sectors</span><span>Government, employers & workers</span><span>Learning by doing</span></div></section>
  <div class="stat-grid"><div class="stat"><strong>5</strong><span>days of learning</span></div><div class="stat"><strong>18</strong><span>workshop sessions</span></div><div class="stat"><strong>${D.activities.length}</strong><span>participant resources</span></div><div class="stat"><strong>6</strong><span>Agreement Lab rounds</span></div></div>
  <div class="section-title"><h2>Your route through the week</h2>${download('downloads/agenda.pdf','Week agenda','button secondary small')}</div>
  <div class="journey">${D.days.map(d=>`<a href="#programme?day=${d.number}" class="day-tile"><small>DAY ${d.number} · ${d.date.toUpperCase()}</small><strong>${d.weekday}</strong><p>${d.theme}</p></a>`).join('')}</div>
  <div class="section-title"><h2>Bring the learning to life</h2></div>
  <div class="grid three"><article class="card"><span class="badge">BEFORE A SESSION</span><h3>Your activity desk</h3><p>Find the shared worksheets and open only your assigned role brief. Everything is organized by day, session and team.</p>${navLink('activities','Find an activity →','button secondary small')}</article><article class="card highlight"><span class="badge">PLAY & DISCUSS</span><h3>Agreement Lab</h3><p>Play two virtual cards. Agree one reason. Six short situations to test your negotiation judgement as a team.</p>${navLink('lab','Enter the Lab →','button small')}</article><article class="card"><span class="badge">TAKE IT HOME</span><h3>My bargaining notebook</h3><p>Prepare interests, evidence, limits and trade-offs. Cost a proposal and export your own working notes.</p>${navLink('notebook','Start preparing →','button secondary small')}</article></div>
  <div class="callout"><strong>Our Return Rule:</strong> anyone can ask us to return to the Common Goals Wall. Read the goals, reconnect with the shared purpose, then resume the hard conversation.</div>
  <div class="grid two"><article class="card"><h3>Use the legal framework well</h3><p>Read the full standards, distinguish Kenya’s ratification status and check who can approve and implement an agreement.</p>${navLink('standards','Explore standards & law →','button secondary small')}</article><article class="card"><h3>A few practical details</h3><p>Sessions begin at 09:00. Monday registration is 08:00–09:00. Friday closes at 12:30. Venue: Naivasha; room assignments are announced by the team.</p><p class="muted">Download resources while connected. Notes stay in this browser until you export or clear them.</p></article></div>`;}
 function programme(){const n=paramNumber('day',5,1)||1,d=D.days[n-1],count=completed.filter(id=>d.sessions.some(s=>s.id===id)).length;return header('Your five-day journey','The week, at a glance','Use each day’s session cards to find activities. The checkboxes are a personal record on this device.')+dayTabs(n,'day')+`
 <div class="day-details"><div><span class="eyebrow">DAY ${n} · ${d.date} 2026</span><h2>${d.theme}</h2></div><div class="progress-wrap"><small>${count} of ${d.sessions.length} sessions marked complete</small><div class="progress"><span style="width:${100*count/d.sessions.length}%"></span></div></div></div>
 ${n===1?'<div class="callout">08:00–09:00 · Monday registration. Opening begins at 09:00.</div>':''}
 <div class="schedule">${d.sessions.map(s=>`<article class="session ${completed.includes(s.id)?'complete':''}"><div class="session-time">${s.time}<small>Session ${s.number}</small></div><div><h3>${s.title}</h3><p>${s.description}</p>${s.id==='d1s1'?navLink('opening','Launch the opening screens →','link'):navLink(`activities?day=${n}&session=${s.number}`,'Get session activities →','link')}</div><input type="checkbox" data-complete="${s.id}" aria-label="Mark ${esc(s.title)} complete" ${completed.includes(s.id)?'checked':''}></article>`).join('')}</div>
 <div class="callout gold">${n===5?'<strong>Friday closes at 12:30.</strong> Complete your sector action plan and evaluation before the closing remarks.':'Coffee: 10:30–11:00 and 15:15–15:45 · Lunch: 12:30–14:00.'}</div><div class="actions">${download('downloads/agenda.pdf','Download the full agenda')}${navLink(`activities?day=${n}`,'All activities for this day','button secondary')}</div>`;}
 const OPENING=[
  {label:'Welcome',title:'Shared purpose. Stronger negotiation.',lead:'Social dialogue in the public health and higher education sectors in Kenya',points:['Naivasha · 12–16 October 2026','A practical week of preparation, conversation and live negotiation']},
  {label:'Who is in the room?',title:'Two sectors. Several perspectives.',lead:'Government, employers’ and workers’ representatives bring different responsibilities and a shared stake in public services.',points:['Public health: access, quality and continuity','Higher education: teaching, research and skills','Listen for both the common ground and the real differences']},
  {label:'Our shared purpose',title:'What should good dialogue protect?',lead:'A better agreement begins with understanding the public purpose, the people delivering it and the people who rely on it.',points:['Quality services for patients, students and communities','Fair work, safe workplaces and a voice in decisions','Commitments that can be implemented and reviewed']},
  {label:'What we will practise',title:'Skills you can use at the next table.',points:['Prepare: interests, evidence, alternatives and mandate','Choose an approach that fits the issue and the relationship','Ask, listen, reframe and create useful options','Close with clear responsibilities, dates and follow-up']},
  {label:'The week ahead',title:'From common ground to real practice.',days:true},
  {label:'How we will work',title:'A room where everyone can learn.',points:['Participate, listen and invite quieter voices','Respect colleagues and the roles they are assigned','Keep colleagues’ real institutional experiences in the room','Arrive on time; practise with curiosity and honest reflection']},
  {label:'Social dialogue',title:'Know which conversation you are having.',points:['Information-sharing: make relevant information available','Consultation: seek and consider views before a decision','Negotiation: seek mutually acceptable terms','Partnership: continue the joint work under agreed arrangements']},
  {label:'A useful preparation lens',title:'Needs. Limits. Options. Implementation.',points:['What matters to each side beneath the demand?','Who has the authority and what can each team agree?','Which differences in priorities create room to trade?','How will the agreement become lawful, funded and real?']},
  {label:'Your dashboard',title:'A desk for the whole week.',points:['The week: session times and the route through the course','Activity desk: worksheets and your own team’s brief','Standards & law: full texts and official reference links','Agreement Lab and notebook: discuss, prepare and export']},
  {label:'Our first step',title:'Find the common ground.',lead:'At 11:00: Our Two Sectors — Common Ground and Shared Goals.',points:['Build the Commonality Market in mixed groups','Write one shared goal, in fifteen words or fewer','Adopt the Return Rule: anyone may ask us to go back to the wall']}
 ];
 const LAUNCH=[{label:'Confirmed launch only',title:'Handbook launch',lead:'ILO Handbook on Social Dialogue in the Health Sector – Kenya',points:['Welcome the confirmed launch speakers','Use the approved physical publication and event arrangements','Connect the launch with this week’s practical learning']},{label:'Guidance into practice',title:'Make dialogue a working process.',points:['Include the people affected by decisions','Clarify responsibilities and decision authority','Record commitments and make follow-up visible']},{label:'Carry the launch into the week',title:'What will we put into practice?',lead:'Identify one process your institution could strengthen through social dialogue.',points:['A conversation that needs a clearer purpose','A decision that needs better participation','A commitment that needs a review point']}];
 function slides(){return launchIncluded?[...OPENING.slice(0,3),...LAUNCH,...OPENING.slice(3)]:OPENING;}
 function opening(){return header('Monday · 09:00–10:30','Open the week from the dashboard','A clean presentation for the opening session. These screens introduce the workshop; confirmed speakers deliver their remarks between screens as appropriate.')+`
 <section class="opening-cover"><div><span class="badge gold">10 OPENING SCREENS</span><h2>Ready for the room.</h2><p>Connect your projector, start the presentation and move through the screens at your own pace. Pause for welcome remarks, introductions and the official photograph as directed.</p><div class="actions"><button class="btn gold" data-present>Start presentation →</button><button class="btn secondary" data-preview>Preview screens</button></div></div><div class="opening-mark" aria-hidden="true">▷</div></section>
 <div class="callout"><strong>Controls:</strong> → / Space for next, ← for previous, Home / End, B to blank the screen, Escape to exit. Use the fullscreen button after starting.</div>
 <label class="checkline"><input type="checkbox" id="include-launch" ${launchIncluded?'checked':''}> Include three handbook launch screens <strong>only if the launch is confirmed</strong>.</label>
 <p class="muted" style="font-size:12px;margin-top:9px">The default opening has ten screens. Launch screens are general event prompts; they do not reproduce the unpublished handbook or establish its contents.</p>
 <div class="section-title"><h2>The opening route</h2><small>${slides().length} screens</small></div><div class="grid two"><div class="card screen-list">${slides().map(s=>`<div class="screen-item">${s.title}</div>`).join('')}</div><div class="card"><h3>Before you begin</h3><p>Open this tab before 09:00, connect the projector and check that the screen is readable from the back. Close unrelated browser tabs and notifications.</p><p>Start on the welcome screen. Keep the mouse over the navigation controls only when needed. B gives a quiet blank screen while someone speaks.</p><p>For a portable backup, open index.html from the downloaded dashboard folder. Keep all files together.</p>${navLink('programme?day=1','See Monday’s agenda →','button secondary small')}</div></div>`;}
 function showPresentation(index=0){openingIndex=index;blank=false;const dialog=$('#presenter');drawSlide();if(!dialog.open)dialog.showModal();}
 function drawSlide(){const arr=slides(),s=arr[openingIndex];$('#presenter').innerHTML=`<div class="slide-shell"><div class="slide-top"><img src="assets/itcilo-logo.png" alt="ITCILO"><span>NAIVASHA · 12–16 OCTOBER 2026</span></div><div class="slide-body"><div class="eyebrow">${s.label}</div><h1>${s.title}</h1>${s.lead?`<p class="slide-lead">${s.lead}</p>`:''}${s.days?`<div class="slide-days">${D.days.map(d=>`<div class="slide-day"><small>${d.weekday}</small><strong>Day ${d.number}</strong><p>${d.theme}</p></div>`).join('')}</div>`:`<ul class="slide-points">${(s.points||[]).map(t=>`<li>${t}</li>`).join('')}</ul>`}</div><div class="slide-bottom"><span class="count">${openingIndex+1} / ${arr.length}</span><span class="keys">← → / Space · B blank · Esc exit</span><div class="actions"><button class="btn" data-slide="prev" ${openingIndex===0?'disabled':''}>← Previous</button><button class="btn" data-slide="next" ${openingIndex===arr.length-1?'disabled':''}>Next →</button><button class="btn" data-fullscreen>Fullscreen</button><button class="btn" data-slide="exit">Exit</button></div></div></div>${blank?'<div class="blank-screen">Press B to return</div>':''}`;}
 function slideStep(direction){if(blank){blank=false;drawSlide();return;}openingIndex=Math.max(0,Math.min(slides().length-1,openingIndex+direction));drawSlide();}
 function closePresentation(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});$('#presenter').close();blank=false;}
 const ROLE_NAMES={shared:'Shared desk',worker:'Worker / union team',employer:'Employer / management team',speaker1:'Round 1 speaker',speaker2:'Round 2 speaker'};
 function activityParams(){const day=paramNumber('day',5),session=paramNumber('session',4);const sector=['both','health','education'].includes(currentParams.get('sector'))?currentParams.get('sector'):'both';const role=Object.hasOwn(ROLE_NAMES,currentParams.get('role'))?currentParams.get('role'):'shared';return {day,session,sector,role,q:currentParams.get('q')||''};}
 function activities(){const f=activityParams(),rows=D.activities.filter(a=>(!f.day||a.day===f.day)&&(!f.session||a.session===f.session)&&(f.sector==='both'||a.sector==='both'||a.sector===f.sector)&&(a.role==='shared'||a.role===f.role)&&(!f.q||(a.title+' '+a.description).toLowerCase().includes(f.q.toLowerCase())));return header('Participant downloads','The activity desk','Choose a day and session, then your assigned team. Shared resources are available to everyone. Open a role brief only when the facilitator assigns it.')+`
 <div class="filters"><label class="field">Day<select id="activity-day"><option value="0">All days</option>${D.days.map(d=>`<option value="${d.number}" ${d.number===f.day?'selected':''}>${d.weekday} · Day ${d.number}</option>`).join('')}</select></label><label class="field">Session<select id="activity-session"><option value="0">All sessions</option>${[1,2,3,4].map(n=>`<option value="${n}" ${n===f.session?'selected':''}>Session ${n}</option>`).join('')}</select></label><label class="field">Sector<select id="activity-sector">${[['both','Both sectors'],['health','Public health'],['education','Higher education']].map(([v,t])=>`<option value="${v}" ${v===f.sector?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">Find a resource<input id="activity-search" type="text" value="${esc(f.q)}" placeholder="e.g. Job Grading"></label></div>
 <div class="tabs" aria-label="Assigned role">${Object.entries(ROLE_NAMES).map(([v,t])=>`<button data-role="${v}" aria-pressed="${v===f.role}">${t}</button>`).join('')}</div>
 ${f.role!=='shared'?`<div class="callout gold"><label class="checkline"><input type="checkbox" id="role-confirm" ${roleConfirmed?'checked':''}> I have been assigned <strong>${ROLE_NAMES[f.role]}</strong> and will open only that role’s brief.</label></div>`:''}
 <p class="muted" style="font-size:12px;margin-bottom:18px">${rows.length} resources shown. Role tabs separate the exercise briefs; this public site does not provide password protection. All scenarios and figures are fictional.</p>
 ${rows.length?`<div class="grid three">${rows.map(a=>`<article class="card resource"><div><span class="badge">DAY ${a.day} · SESSION ${a.session}</span>${a.role!=='shared'?'<span class="badge role">ASSIGNED ROLE</span>':''}</div><h3>${a.title}</h3><p>${a.description}</p><small class="muted">${a.pages} ${a.pages===1?'page':'pages'} · ${a.sector==='health'?'Public health':a.sector==='education'?'Higher education':'Both sectors'}</small><div class="actions">${a.role==='shared'||roleConfirmed?download(a.file):'<button class="btn small" disabled>Confirm role to download</button>'}${a.role==='shared'||roleConfirmed?`<button class="btn secondary small" data-view-activity="${a.id}">View</button>`:''}</div></article>`).join('')}</div>`:'<div class="empty">No resources match these filters. Try both sectors, all sessions or a different day.</div>'}
 <div class="callout">For Extracting Needs, use <strong>Both sectors</strong>: the Round 1 and Round 2 speaker scenarios differ. Swap roles after eight minutes; read each speaker brief only when it is your turn.</div><div class="actions">${download('downloads/agenda.pdf','Download agenda')}${navLink('lab','Play virtual cards →')}${download('downloads/agreement-lab-cards.pdf','Optional printable cards','button secondary')}</div>`;}
 const LAW=[
  ['Rights and bargaining','Article 41 distinguishes workers’ rights, employers’ organizational rights and the right of unions, employers’ organizations and employers to collective bargaining.','https://new.kenyalaw.org/akn/ke/act/2010/constitution/eng@2010-09-03','Constitution · Articles 41 and 230'],
  ['From agreement to registration','Labour Relations Act sections 59(5) and 60: registration in the Employment and Labour Relations Court; submission within fourteen days. Employer first, union if the employer fails.','https://new.kenyalaw.org/akn/ke/act/2007/14/eng@2022-12-31','Labour Relations Act'],
  ['SRC advice has legal effect','The Supreme Court held on 30 May 2025 that SRC advice on other public officers’ remuneration is binding in the NHIF case. Check the advice, coverage and lawful approval route.','https://new.kenyalaw.org/akn/ke/judgment/kesc/2025/37/eng@2025-05-30','Supreme Court · [2025] KESC 37'],
  ['County wage-bill denominator','Regulation 25(1)(b) sets a 35% limit for county wages and benefits against total county revenue, excluding extractive natural resources revenue. It is not a university recurrent-budget rule.','https://new.kenyalaw.org/akn/ke/act/ln/2015/35','PFM (County Governments) Regulations'],
  ['Essential services differ','Section 81 and the Fourth Schedule include hospital services. Do not apply the same strike restriction to every higher education occupation without checking the applicable law and orders.','https://new.kenyalaw.org/akn/ke/act/2007/14/eng@2022-12-31','Labour Relations Act · section 81'],
  ['Higher education standard','The 1997 Recommendation remains the reference here. Formal revision consultations do not themselves adopt a replacement; a draft is distinct from the adopted instrument.','https://www.unesco.org/en/higher-education/1997recommendation/formal-consultations','UNESCO · revision consultations']
 ];
 function standards(){const query=currentParams.get('q')||'',group=currentParams.get('group')||'All',normalize=s=>s.toLowerCase().replace(/\bc0+(\d+)/g,'c$1');const rows=D.standards.filter(s=>(group==='All'||s.group===group)&&normalize(s.code+' '+s.title+' '+s.summary).includes(normalize(query)));return header('Full texts · Kenya’s position','Standards & law','Read the instrument, then connect it to the actual worker group, legal duty and institution. Status checked 30 September 2026; use NORMLEX to check for subsequent changes.')+`
 <div class="callout"><strong>Three distinctions:</strong> ratified Conventions create treaty obligations; unratified Conventions can inform policy and practice; Recommendations are guidance, not ratifiable treaties. ILO membership also carries fundamental principles and rights at work.</div>
 <div class="filters" style="grid-template-columns:1fr 2fr"><label class="field">Theme<select id="standard-group">${['All','Bargaining','Equality','Safety & dignity','Sector standards'].map(g=>`<option ${g===group?'selected':''}>${g}</option>`).join('')}</select></label><label class="field">Search instrument<input id="standard-search" type="text" value="${esc(query)}" placeholder="e.g. C87, C190, nursing, higher education"></label></div>
 <p class="muted" style="font-size:12px;margin-bottom:19px">${rows.length} instruments shown · 17 complete PDFs available here · C155 and C187 full texts open on NORMLEX. C190 and R206 PDFs contain the authentic English and French texts.</p>
 <div class="grid three">${rows.map(s=>`<article class="card resource standard-card"><div><span class="badge">${s.code} · ${s.year}</span></div><h3>${s.title}</h3><span class="status ${s.status.startsWith('Not')?'unratified':''}">${s.status}</span><p>${s.summary}</p><div class="actions">${s.file?download(s.file):''}${s.file?`<button class="btn secondary small" data-view-standard="${s.code}">Read full text</button>`:''}<a class="${s.file?'link':'button small'}" href="${s.url}" target="_blank" rel="noopener">${s.file?'Official source ↗':'Full official text ↗'}</a></div></article>`).join('')}</div>
 <div class="section-title"><h2>Kenya: six checks before signing</h2></div><div class="law-grid">${LAW.map(([t,b,u,l])=>`<article class="card"><h3>${t}</h3><p>${b}</p><a href="${u}" target="_blank" rel="noopener">${l} ↗</a></article>`).join('')}</div>
 <div class="callout gold">Simulation mandates and invented figures do not replace actual law. For a real agreement, verify recognition, authority, applicable SRC advice, lawful funding, approvals, registration and implementation duties.</div><div class="actions"><a class="button secondary small" href="https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:11200:0::NO::P11200_COUNTRY_ID:103315" target="_blank" rel="noopener">Kenya ratifications ↗</a><a class="button secondary small" href="https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:11210:0::NO::P11210_COUNTRY_ID:103315" target="_blank" rel="noopener">Kenya non-ratifications ↗</a></div>`;}
 function viewPdf(file,title,url=''){const dialog=$('#viewer');$('#viewer-title').textContent=title;$('#viewer-content').innerHTML=`<div class="pdf-links"><a href="${esc(file)}" download>Download PDF ↓</a><a href="${esc(file)}" target="_blank" rel="noopener">Open in a separate tab ↗</a>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">Official source ↗</a>`:''}</div><iframe title="${esc(title)}" src="${esc(file)}"></iframe>`;dialog.showModal();}
 const NOTE_FIELDS=[['purpose','Our purpose / shared goal'],['mandate','Our authority, mandate and approval route'],['batna','Our BATNA: what we can actually do without a deal'],['counterpart','Their likely interests, constraints and alternatives'],['roles','Who leads, records, watches and decides'],['moment','When tension rises, we will…'],['priority1','Improvement priority 1: when X, I will Y'],['priority2','Improvement priority 2: when X, I will Y']];
 const ISSUE_FIELDS=[['issue','The specific issue'],['position','Our position'],['interest','Our underlying interest'],['limit','Our limit / walk-away'],['their','Their position and likely interest'],['evidence','Evidence: source, scope, denominator and period'],['approach','Our approach and reason'],['trade','Trade-off and what we need in return']];
 function noteField(k,t){return `<label class="field">${t}<textarea data-note="${k}" placeholder="Write your own working notes…">${esc(notes[k]||'')}</textarea></label>`;}
 function notebook(){return header('Preparation you can keep','My bargaining notebook','Prepare before you sit down. These notes are saved only in this browser on this device. Export a copy to keep or share; avoid names, personal cases or sensitive institutional details.')+`
 <div class="actions"><button class="btn" data-export-notes>Export my notebook ↓</button>${download('downloads/activities/bargaining-notebook.pdf','Download paper notebook','button secondary')}<button class="btn danger" data-clear-notes>Clear notes on this device</button></div>
 <div class="callout"><strong>Shared device?</strong> Export your work, then clear your notebook, game and personal session checks before handing over. Nothing is submitted to the workshop team.</div>
 <section class="card"><h2>Prepare the whole negotiation</h2><div class="note-fields">${NOTE_FIELDS.map(([k,t])=>noteField(k,t)).join('')}</div></section>
 ${[1,2,3].map(n=>`<details class="card issue" ${n===1?'open':''}><summary>Issue ${n} · interests, evidence and trade-offs</summary><div class="note-fields">${ISSUE_FIELDS.map(([k,t])=>noteField('issue'+n+'-'+k,t)).join('')}</div></details>`).join('')}
 <section class="card calculator"><span class="badge">ILLUSTRATIVE COSTING</span><h2>What does a pay proposal cost?</h2><p>Estimate the incremental annual pay cost and historic arrears separately. These are sample inputs, not figures for any institution. This calculator does not determine affordability or legal authority.</p><div class="calc-fields">${[['staff','Number of staff',1200,1],['salary','Monthly base pay · KSh',20000,.01],['rise','Increase · %',7,.01],['months','Arrears months',18,1],['oncost','Employer on-cost · %',0,.01],['budget','Relevant annual budget · KSh (optional)',0,.01]].map(([k,t,v,step])=>`<label class="field">${t}<input type="number" data-calc="${k}" value="${v}" min="0" ${k==='oncost'?'max="100"':''} step="${step}"></label>`).join('')}</div><div id="calc-error" class="error" role="status"></div><div class="calc-results" id="calc-results"></div><p style="font-size:12px;margin-top:16px">First-year estimate = 12 months of the incremental pay cost + stated arrears, with the chosen on-cost applied. It excludes existing salary, unrelated claims, compounding, interest, deductions and other charges. Check on-cost treatment of arrears and the actual budget period.</p></section>`;}
 function calculate(){const inputs=$$('[data-calc]');if(!inputs.length)return;const v={};inputs.forEach(el=>v[el.dataset.calc]=el.value===''?NaN:Number(el.value));let error='';if(Object.values(v).some(n=>!Number.isFinite(n)||n<0))error='Enter a non-negative number in every field. Use 0 for an optional budget.';else if(!Number.isInteger(v.staff)||!Number.isInteger(v.months))error='Staff and arrears months must be whole numbers.';else if(v.oncost>100)error='Employer on-cost must be between 0 and 100%.';const increment=v.staff*v.salary*v.rise/100,annual=increment*12,arrears=increment*v.months,total=(annual+arrears)*(1+v.oncost/100);if(!error&&![increment,annual,arrears,total].every(Number.isFinite))error='These inputs are too large to calculate.';$('#calc-error').textContent=error;if(error){$('#calc-results').innerHTML='';return;}const money=n=>'KSh '+n.toLocaleString('en-KE',{maximumFractionDigits:2});$('#calc-results').innerHTML=[['Monthly increment',money(increment)],['Annual increment',money(annual)],['Arrears before on-cost',money(arrears)],['First-year estimate',money(total)]].map(([t,n])=>`<div class="calc-result"><small>${t}</small><strong>${n}</strong></div>`).join('')+(v.budget?`<p style="grid-column:1/-1;font-size:13px">First-year estimate / your stated annual budget: <strong>${(100*total/v.budget).toFixed(2)}%</strong>. Confirm that this is a comparable denominator.</p>`:'');}
 function notebookExport(){let out='# My bargaining notebook\nNaivasha · 12–16 October 2026\n\n';for(const [k,t] of NOTE_FIELDS)out+=`## ${t}\n${notes[k]||''}\n\n`;for(let n=1;n<=3;n++){out+=`## Issue ${n}\n\n`;for(const [k,t] of ISSUE_FIELDS)out+=`### ${t}\n${notes['issue'+n+'-'+k]||''}\n\n`;}exportText('Naivasha-My-Bargaining-Notebook.md',out);}
 const ORDERS=[[2,0,1],[1,2,0],[0,2,1],[2,1,0],[1,0,2],[0,2,1]];
 function roundState(){const n=game.current;if(!game.rounds[n]||typeof game.rounds[n]!=='object')game.rounds[n]={selected:[],reason:'',revealed:false,deadline:0};const s=game.rounds[n];if(!Array.isArray(s.selected))s.selected=[];s.selected=[...new Set(s.selected.filter(i=>[0,1,2].includes(i)))].slice(0,2);s.deadline=Number.isFinite(s.deadline)&&s.deadline>0?s.deadline:0;if(!Number.isFinite(s.remaining)||s.remaining<0)s.remaining=90000;if(!Array.isArray(s.fronts))s.fronts=[];return s;}
 function score(){return D.rounds.reduce((total,r,i)=>{const s=game.rounds[i];return total+(s?.revealed&&Array.isArray(s.selected)?[...new Set(s.selected)].slice(0,2).filter(n=>r.cards[n]?.good).length:0);},0);}
 function gameMode(){return ['team','projector'].includes(currentParams.get('play'))?currentParams.get('play'):'';}
 function readyToReveal(){const s=roundState();return s.selected.length===2&&(String(s.reason||'').trim()||(gameMode()==='projector'&&s.reasonAloud));}
 function gameDone(){return D.rounds.filter((_,i)=>game.rounds[i]?.revealed).length;}
 const ROUND_LABELS=['Listen','Evidence','Mandate','Safe voice','De-escalate','Close'];
 function moveLetter(i){return String.fromCharCode(65+ORDERS[game.current].indexOf(i));}
 function lab(){
  if(gameMode())return currentParams.get('view')==='results'&&gameDone()===6?gameResults():gameTable();
  lastDealtRound=null;
  return header('Virtual cards · real discussion','Agreement Lab','Play entirely on screen. Deal three negotiation moves, choose two as a team and explain why. Reveal the feedback, then carry one useful move to your next negotiation.')+`
  <section class="game-cover"><div class="game-cover-copy"><span class="badge gold">6 CHALLENGES · 18 VIRTUAL MOVE CARDS</span><h2>Put your next move<br>on the table.</h2><p>A virtual card game for public health and higher education. Click or tap the cards; your chosen pair appears on the table. No printing is needed.</p><div class="game-cover-stats"><span><strong>2</strong> moves to play</span><span><strong>1</strong> shared reason</span><span><strong>6</strong> rounds to discuss</span></div></div><div class="cover-deck" aria-hidden="true"><div class="cover-card cover-card-one"><span>A</span><b>Ask what matters</b><i>LISTEN</i></div><div class="cover-card cover-card-two"><span>B</span><b>Check the source</b><i>EVIDENCE</i></div><div class="cover-card cover-card-three"><span>C</span><b>Find the authority</b><i>MANDATE</i></div></div></section>
  <div class="game-setup"><label class="field">Team name (optional)<input id="team-name" type="text" maxlength="60" value="${esc(game.team)}" placeholder="e.g. Team Lakeview" autocomplete="off"></label><div class="saved-game"><strong>${gameDone()} / 6 rounds discussed</strong><span>${score()} / 12 learning points · saved on this device</span></div></div>
  <div class="grid two game-modes"><article class="card"><span class="badge">ONE DEVICE PER TEAM</span><h3>Team Challenge</h3><p>Teams of 3–5 discuss the virtual hand, choose two cards and write one reason. Use the optional timer and compare learning points during the debrief.</p><button class="btn" data-start-game="team">${gameDone()?'Continue':'Start'} Team Challenge →</button></article><article class="card highlight"><span class="badge">WHOLE-ROOM PLAY</span><h3>Projector Table</h3><p>You control the cards on the big screen. Invite the room to choose two moves and explain its reasoning aloud, then flip the cards to discuss the feedback.</p><button class="btn" data-start-game="projector">Open Projector Table →</button></article></div>
  <div class="callout"><strong>How to play:</strong> read the situation → select two cards → agree one reason → reveal and discuss → move to the next round. Selected cards can be changed until feedback is revealed. One round: 10–15 minutes; all six: 45–60 minutes.</div>
  <div class="section-title"><h2>The six challenges</h2><small>Play in order, or choose today’s round</small></div><div class="challenge-list">${D.rounds.map((r,i)=>`<button data-launch-round="${i}"><span class="challenge-number">${game.rounds[i]?.revealed?'✓':i+1}</span><span><strong>${r.title}</strong><small>Suggested day ${r.day} · ${game.rounds[i]?.revealed?'feedback available':'ready to play'}</small></span><span aria-hidden="true">→</span></button>`).join('')}</div>
  <section class="card reflection"><h3>What will we take to the table?</h3><p>Save a team takeaway and export your choices. Each team plays its own copy; devices do not share a live game.</p><label class="field">Our takeaway<textarea id="game-reflection" placeholder="One move we will try; one assumption we will check…">${esc(game.reflection)}</textarea></label><div class="actions"><button class="btn" data-export-game>Export team reflection ↓</button>${download('downloads/agreement-lab-cards.pdf','Optional printable backup','button secondary')}<button class="btn danger" data-reset-game>Reset game</button></div></section><p class="game-note">All situations are fictional. Points are discussion prompts, not a competency assessment. Progress saves in this browser; export before switching devices.</p>`;
 }
 function gameToolbar(){return `<header class="game-toolbar"><div class="game-brand"><img src="assets/itcilo-logo.png" alt="ITCILO"><div><h1>Agreement Lab</h1><span>${gameMode()==='projector'?'PROJECTOR TABLE':'TEAM CHALLENGE'} · ${esc(game.team||'Naivasha 2026')}</span></div></div><div class="actions"><button class="btn game-control" data-game-help aria-expanded="${gameHelp}">How to play</button><button class="btn game-control" data-game-fullscreen>Fullscreen</button><button class="btn game-control" data-exit-game>Exit table</button></div></header>`;}
 function gameInstructions(){return gameHelp?`<aside class="game-instructions"><h2>One hand. Two moves. One reason.</h2><ol><li>Read the situation together.</li><li>Click or tap two cards. Click a selected card again to return it to the hand.</li><li>${gameMode()==='projector'?'Invite a spoken reason and tick the confirmation, or type one sentence.':'Write your team’s reason before revealing feedback.'}</li><li>Reveal the feedback. Click a card to flip between its move and the feedback.</li><li>Discuss what you would check at your own institution, then continue.</li></ol><p>Timer optional: start, pause, add 30 seconds or reset. Reaching zero never locks play. Keyboard: 1 / 2 / 3 select or flip cards; F fullscreen; Escape exits. Each device saves its own progress.</p><button class="btn secondary small" data-game-help>Close instructions</button></aside>`:'';}
 function gameTrack(){return `<nav class="game-track" aria-label="Six negotiation rounds">${D.rounds.map((r,i)=>`<button data-round="${i}" class="${i===game.current?'current':''} ${game.rounds[i]?.revealed?'done':''}" aria-label="Round ${i+1}: ${r.title}${game.rounds[i]?.revealed?', discussed':''}" aria-pressed="${i===game.current}"><span>${game.rounds[i]?.revealed?'✓':String(i+1).padStart(2,'0')}</span><strong>${ROUND_LABELS[i]}</strong></button>`).join('')}</nav>`;}
 function virtualCard(i,j,s,r){const c=r.cards[i],picked=s.selected.includes(i),flipped=s.revealed&&!s.fronts.includes(i),letter=String.fromCharCode(65+j);return `<button class="virtual-card ${picked?'selected':''} ${flipped?'is-flipped':''}" ${s.revealed?`data-flip="${i}"`:`data-move="${i}"`} aria-pressed="${picked}" aria-label="${s.revealed?(flipped?'Show move':'Show feedback'):(picked?'Return':'Select')} card ${letter}: ${esc(c.title)}"><span class="virtual-card-inner"><span class="card-face card-front" ${flipped?'aria-hidden="true"':''}><span class="card-corner">${letter}<small>MOVE</small></span><span class="card-tag">${ROUND_LABELS[game.current]}</span><strong>${c.title}</strong><span class="card-copy">${c.text}</span><span class="card-action">${s.revealed?'Click to see feedback ↻':picked?'✓ On the table · click to return':'+ Play this card'}</span></span>${s.revealed?`<span class="card-face card-back ${c.good?'supported':'reconsider'}" ${!flipped?'aria-hidden="true"':''}><span class="card-corner">${letter}<small>REVIEW</small></span><span class="card-tag">${picked?'YOUR CHOICE':'NOT SELECTED'}</span><strong>${c.good?'Supported move':'Reconsider this move'}</strong><span class="feedback">${c.why}</span><span class="review-title">${c.title}</span><span class="card-action">Click to see the move ↻</span></span>`:''}</span></button>`;}
 function gameTable(){const n=game.current,r=D.rounds[n],s=roundState(),deal=lastDealtRound!==n;lastDealtRound=n;return `<section class="virtual-game ${gameMode()==='projector'?'projector-mode':''}"><div class="game-frame">${gameToolbar()}${gameInstructions()}${gameTrack()}
 <div class="game-status"><span><strong>${gameDone()} / 6</strong> rounds discussed</span><span><strong>${score()} / 12</strong> learning points</span><span class="status-hint">${s.revealed?'Feedback revealed · tap a card to flip it':'Play two moves. Explain your choice.'}</span></div>
 <section class="table-scenario" aria-labelledby="round-title"><div><span class="eyebrow">ROUND ${n+1} OF 6 · SUGGESTED DAY ${r.day}</span><h2 id="round-title">${r.title}</h2><p>${r.situation}</p></div><div class="table-timer"><span class="timer-caption">OPTIONAL DISCUSSION TIMER</span><strong id="timer-value">${timeText(s.deadline?Math.max(0,s.deadline-Date.now()):s.remaining)}</strong><div class="timer-controls"><button data-timer ${s.revealed?'disabled':''}>${s.deadline?'Pause':s.remaining===0?'Restart 90s':s.remaining===90000?'Start 90s':'Resume'}</button><button data-add-time ${s.revealed?'disabled':''}>+30s</button><button data-reset-timer ${s.revealed?'disabled':''} aria-label="Reset timer to 90 seconds">↺</button></div><small id="timer-message">${s.revealed?'Round discussed':s.deadline&&s.deadline<=Date.now()||!s.deadline&&s.remaining===0?'Time is up — keep discussing':'The timer never locks play'}</small></div></section>
 <div class="hand-heading"><h3>${s.revealed?'Flip and discuss the cards':'Your virtual hand'}</h3><span>${s.selected.length} / 2 cards on the table</span></div><div class="virtual-hand ${deal?'deal-hand':''}" aria-label="Three move cards">${ORDERS[n].map((i,j)=>virtualCard(i,j,s,r)).join('')}</div>
 <section class="response-table" aria-label="Your chosen pair and reason"><div class="chosen-pair"><span class="response-label">YOUR TWO MOVES</span><div class="chosen-slots">${[0,1].map(slot=>{const i=s.selected[slot];return i===undefined?`<div class="chosen-slot empty-slot"><span>+</span><small>Choose move ${slot+1}</small></div>`:`<div class="chosen-slot"><b>${moveLetter(i)}</b><strong>${r.cards[i].title}</strong>${!s.revealed?`<button data-move="${i}" aria-label="Return ${esc(r.cards[i].title)} to the hand">×</button>`:'<span aria-label="Selected">✓</span>'}</div>`;}).join('')}</div></div><div class="table-reason"><label for="round-reason">Our reason: why these two?</label><textarea id="round-reason" rows="2" ${s.revealed?'readonly':''} placeholder="Agree one sentence…">${esc(s.reason||(s.revealed&&s.reasonAloud?'Discussed aloud on the projector.':''))}</textarea>${gameMode()==='projector'?`<label class="spoken-reason"><input type="checkbox" id="reason-aloud" ${s.reasonAloud?'checked':''} ${s.revealed?'disabled':''}> We explained our reason aloud.</label>`:''}</div></section>
 <footer class="table-footer"><div><strong>${s.revealed?`${s.selected.filter(i=>r.cards[i].good).length} / 2 learning points this round`:'Discuss first. Then reveal.'}</strong><p>${s.revealed?'What evidence, authority or timing would change your choices?':'Selected cards can be changed until feedback is revealed.'}</p></div><div class="actions">${s.revealed?`<button class="btn game-control" data-flip-all>${s.fronts.length===3?'Show feedback':'Show moves'} ↻</button>${gameDone()===6?'<button class="btn gold" data-game-results>See our results →</button>':'<button class="btn gold" data-next-round>Next round →</button>'}`:`<button class="btn gold" data-reveal ${readyToReveal()?'':'disabled'}>Reveal & discuss →</button>`}</div></footer><p class="table-footnote">Fictional training situations · learning points are not a competency assessment · progress saves on this device</p>
 </div></section>`;}
 function gameResults(){return `<section class="virtual-game"><div class="game-frame">${gameToolbar()}${gameInstructions()}<section class="game-results"><span class="badge gold">ALL SIX ROUNDS DISCUSSED</span><h2>Take your next move<br>back to the table.</h2><div class="result-points"><strong>${score()} <span>/ 12</span></strong><p>learning points<br><small>A prompt for reflection, not a measure of competence.</small></p></div><div class="result-rounds">${D.rounds.map((r,i)=>{const s=game.rounds[i];return `<button data-round="${i}"><span>${i+1}</span><strong>${r.title}</strong><b>${s.selected.filter(n=>r.cards[n]?.good).length} / 2</b><small>Review →</small></button>`;}).join('')}</div><label class="field">Our takeaway<textarea id="game-reflection" placeholder="One move we will try; one assumption we will check…">${esc(game.reflection)}</textarea></label><div class="result-prompts"><p>Which move would you repeat at your next negotiation?</p><p>What information or authority would you check first?</p><p>How would you record and follow up the agreement?</p></div><div class="actions"><button class="btn gold" data-export-game>Export team reflection ↓</button><button class="btn game-control" data-exit-game>Back to Agreement Lab</button><button class="btn game-control" data-reset-game>Reset game</button></div><p class="table-footnote">Each team plays its own copy. Compare reflections together; game state is not shared between devices.</p></section></div></section>`;}
 function refreshGame(focusSelector){render();if(focusSelector)$(focusSelector)?.focus({preventScroll:true});}
 function chooseMove(i){const s=roundState();if(s.revealed)return;if(s.selected.includes(i))s.selected=s.selected.filter(n=>n!==i);else if(s.selected.length<2)s.selected.push(i);else{toast('Two cards are on the table. Return one before choosing another.');return;}write('game',game);refreshGame(`[data-move="${i}"]`);}
 function gameFullscreen(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>toast('Fullscreen is unavailable. Use your browser’s fullscreen control (F11 on Windows).'));else toast('Use your browser’s fullscreen control (F11 on Windows).');}
 function exitGame(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});go('lab');}
 function timeText(ms){const seconds=Math.ceil(ms/1000);return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
 function startTimerDisplay(){const update=()=>{const el=$('#timer-value');if(!el)return;const s=roundState(),remaining=s.deadline?Math.max(0,s.deadline-Date.now()):s.remaining;el.textContent=timeText(remaining);el.classList.toggle('time-up',!s.revealed&&remaining===0);if(!s.revealed&&remaining===0){$('#timer-message').textContent='Time is up — keep discussing';if(s.deadline){s.deadline=0;s.remaining=0;write('game',game);const btn=$('[data-timer]');if(btn)btn.textContent='Restart 90s';}}};update();timer=setInterval(update,500);}
 function gameExport(){let out='# Agreement Lab: team reflection\n\nTeam: '+(game.team||'Unnamed')+'\nLearning points: '+score()+'/12\nRounds discussed: '+gameDone()+'/6\n\n';D.rounds.forEach((r,i)=>{const s=game.rounds[i];out+=`## Round ${i+1}: ${r.title}\n${r.situation}\n\nSelected moves: ${(s?.selected||[]).map(n=>r.cards[n]?.title||'').join('; ')}\nReason: ${s?.reason|| (s?.reasonAloud?'Discussed aloud on the projector.':'')}\nFeedback revealed: ${s?.revealed?'Yes':'No'}\n\n`;});out+='## Our takeaway\n'+(game.reflection||'');exportText('Naivasha-Agreement-Lab-Reflection.md',out);}
 function setActivityFilter(key,value){const f=activityParams();if(['day','session','sector','role'].includes(key))roleConfirmed=false;if(key==='day')f.session=0;f[key]=value;go('activities',f);}
 document.addEventListener('click',e=>{
  const t=e.target.closest('button');if(!t)return;
  if(t.dataset.day)go('programme',{day:t.dataset.day});
  if(t.hasAttribute('data-present')||t.hasAttribute('data-preview'))showPresentation(0);
  if(t.dataset.slide==='next')slideStep(1);if(t.dataset.slide==='prev')slideStep(-1);if(t.dataset.slide==='exit')closePresentation();
  if(t.hasAttribute('data-fullscreen')){const dialog=$('#presenter');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else dialog.requestFullscreen?.().catch(()=>toast('Fullscreen is unavailable. Use your browser’s fullscreen control.'));}
  if(t.dataset.role)setActivityFilter('role',t.dataset.role);
  if(t.dataset.viewActivity){const a=D.activities.find(a=>a.id===t.dataset.viewActivity);if(a&&(a.role==='shared'||roleConfirmed))viewPdf(a.file,a.title);}
  if(t.dataset.viewStandard){const s=D.standards.find(s=>s.code===t.dataset.viewStandard);if(s?.file)viewPdf(s.file,s.code+' · '+s.title,s.url);}
  if(t.dataset.close){$('#'+t.dataset.close).close();$('#viewer-content').innerHTML='';}
  if(t.hasAttribute('data-export-notes'))notebookExport();
  if(t.hasAttribute('data-clear-notes')&&confirm('Clear notebook notes, game data and personal session checks on this device? Export first if you want to keep them.')){notes={};completed=[];game={current:0,rounds:{},team:'',reflection:''};write('notes',notes);write('completed',completed);write('game',game);render();toast('Personal data cleared on this device.');}
  if(t.dataset.startGame)go('lab',{play:t.dataset.startGame});
  if(t.hasAttribute('data-launch-round')){game.current=Number(t.dataset.launchRound);write('game',game);go('lab',{play:'team'});}
  if(t.hasAttribute('data-exit-game'))exitGame();
  if(t.hasAttribute('data-game-fullscreen'))gameFullscreen();
  if(t.hasAttribute('data-game-help')){gameHelp=!gameHelp;refreshGame('[data-game-help]');}
  if(t.hasAttribute('data-round')){game.current=Number(t.dataset.round);write('game',game);if(currentParams.get('view'))go('lab',{play:gameMode()});else refreshGame(`[data-round="${game.current}"]`);}
  if(t.hasAttribute('data-move'))chooseMove(Number(t.dataset.move));
  if(t.hasAttribute('data-flip')){const s=roundState(),i=Number(t.dataset.flip);if(s.revealed){s.fronts=s.fronts.includes(i)?s.fronts.filter(n=>n!==i):[...s.fronts,i];write('game',game);refreshGame(`[data-flip="${i}"]`);}}
  if(t.hasAttribute('data-flip-all')){const s=roundState();s.fronts=s.fronts.length===3?[]:[0,1,2];write('game',game);refreshGame('[data-flip-all]');}
  if(t.hasAttribute('data-reveal')){const s=roundState();if(readyToReveal()&&!s.revealed){s.revealed=true;s.deadline=0;s.remaining=90000;s.fronts=[];write('game',game);refreshGame('[data-flip-all]');}}
  if(t.hasAttribute('data-next-round')){let next=(game.current+1)%6;for(let count=0;count<6&&game.rounds[next]?.revealed;count++)next=(next+1)%6;game.current=next;write('game',game);refreshGame(`[data-round="${next}"]`);window.scrollTo(0,0);}
  if(t.hasAttribute('data-game-results'))go('lab',{play:gameMode(),view:'results'});
  if(t.hasAttribute('data-timer')){const s=roundState();if(s.revealed)return;if(s.deadline){s.remaining=Math.max(0,s.deadline-Date.now());s.deadline=0;}else{s.deadline=Date.now()+(s.remaining||90000);}write('game',game);refreshGame('[data-timer]');}
  if(t.hasAttribute('data-add-time')){const s=roundState();if(s.revealed)return;if(s.deadline)s.deadline=Math.max(Date.now(),s.deadline)+30000;else s.remaining+=30000;write('game',game);refreshGame('[data-add-time]');}
  if(t.hasAttribute('data-reset-timer')){const s=roundState();if(s.revealed)return;s.deadline=0;s.remaining=90000;write('game',game);refreshGame('[data-reset-timer]');}
  if(t.hasAttribute('data-export-game'))gameExport();
  if(t.hasAttribute('data-reset-game')&&confirm('Reset every round and clear the team reflection on this device?')){game={current:0,rounds:{},team:'',reflection:''};lastDealtRound=null;write('game',game);if(currentParams.get('view'))go('lab',{play:gameMode()});else render();}
 });
 document.addEventListener('change',e=>{
  const t=e.target;
  if(t.dataset.complete){completed=completed.filter(id=>id!==t.dataset.complete);if(t.checked)completed.push(t.dataset.complete);write('completed',completed);render();}
  if(t.id==='include-launch'){launchIncluded=t.checked;render();}
  if(t.id==='reason-aloud'){roundState().reasonAloud=t.checked;write('game',game);const btn=$('[data-reveal]');if(btn)btn.disabled=!readyToReveal();}
  if(t.id==='role-confirm'){roleConfirmed=t.checked;render();}
  if(t.id==='activity-day')setActivityFilter('day',t.value);
  if(t.id==='activity-session')setActivityFilter('session',t.value);
  if(t.id==='activity-sector')setActivityFilter('sector',t.value);
  if(t.id==='activity-search')setActivityFilter('q',t.value);
  if(t.id==='standard-group')go('standards',{group:t.value,q:currentParams.get('q')||''});
  if(t.id==='standard-search')go('standards',{group:currentParams.get('group')||'All',q:t.value});
 });
 document.addEventListener('input',e=>{
  const t=e.target;if(t.dataset.note){notes[t.dataset.note]=t.value;write('notes',notes);}
  if(t.dataset.calc)calculate();
  if(t.id==='team-name'){game.team=t.value;write('game',game);}
  if(t.id==='game-reflection'){game.reflection=t.value;write('game',game);}
  if(t.id==='round-reason'){const s=roundState();s.reason=t.value;write('game',game);const btn=$('[data-reveal]');if(btn)btn.disabled=!readyToReveal();}
 });
 document.addEventListener('keydown',e=>{if(currentRoute!=='lab'||!gameMode()||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'){e.preventDefault();exitGame();return;}if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key.toLowerCase()==='f'){e.preventDefault();gameFullscreen();return;}if(currentParams.get('view')==='results')return;if(['1','2','3'].includes(e.key)){e.preventDefault();const i=ORDERS[game.current][Number(e.key)-1];const card=$(`[data-move="${i}"]`)||$(`[data-flip="${i}"]`);card?.click();}if(e.key==='ArrowRight'&&roundState().revealed){e.preventDefault();const next=$('[data-next-round]')||$('[data-game-results]');next?.click();}});
 document.addEventListener('keydown',e=>{if(!$('#presenter').open)return;if(e.key==='Escape'){e.preventDefault();closePresentation();return;}if(e.key==='b'||e.key==='B'){e.preventDefault();blank=!blank;drawSlide();return;}if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();slideStep(1);}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();slideStep(-1);}if(e.key==='Home'){e.preventDefault();openingIndex=0;blank=false;drawSlide();}if(e.key==='End'){e.preventDefault();openingIndex=slides().length-1;blank=false;drawSlide();}});
 $('#presenter').addEventListener('cancel',e=>{e.preventDefault();closePresentation();});
 $('#viewer').addEventListener('close',()=>$('#viewer-content').innerHTML='');
 window.addEventListener('hashchange',()=>{roleConfirmed=false;render();window.scrollTo(0,0);});
 render();
 if('serviceWorker' in navigator&&['http:','https:'].includes(location.protocol))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
