'use strict';
(() => {
  const ORIGIN='https://platform-grievance-india.darrin-dookie.chatgpt.site';
  const API=ORIGIN+'/api/kenya/race';
  const clone=value=>JSON.parse(JSON.stringify(value));
  class RaceConnection {
    constructor(game){this.game=game;this.key='naivasha-race-v1-'+game;this.connection=null;this.pending=null;this.flushing=false;this.polling=false;this.paused=true;this.status='practice';this.offset=0;this.onReset=()=>{};this.onStatus=()=>{};this.onAck=()=>{};try{const saved=JSON.parse(localStorage.getItem(this.key));if(saved&&/^[a-f0-9]{64}$/.test(saved.token)&&saved.game===game){this.connection=saved;this.pending=saved.pending||null;}}catch{} }
    save(){try{if(this.connection)localStorage.setItem(this.key,JSON.stringify({...this.connection,pending:this.pending}));}catch{} }
    active(){return !!this.connection&&!this.paused;}
    setStatus(status,message=''){this.status=status;this.message=message;this.onStatus(status,message);}
    async request(action,body,token=this.connection?.token){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(API+'?action='+action,{signal:controller.signal,method:body?'POST':'GET',mode:'cors',credentials:'omit',cache:'no-store',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await response.json();}catch{throw new Error('The race service did not return a usable response.');}if(!response.ok){const error=new Error(data.error||'Could not connect to the race.');error.status=response.status;error.data=data;throw error;}this.offset=data.serverNow-Date.now();return data;}finally{clearTimeout(timeout);}}
    randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');}
    async join({room,name,sector='health'}){room=String(room).trim().toUpperCase();if(!/^[A-Z2-9]{8}$/.test(room))throw new Error('Enter the eight-character session code from your facilitator.');const same=this.connection?.room===room;const candidate=same?this.connection:{token:this.randomToken(),game:this.game,room,generation:1,name,sector};if(!same)this.pending=null;this.connection=candidate;this.save();this.setStatus('connecting');try{const data=await this.request('join',{room,game:this.game,name,sector},candidate.token);this.connection={...candidate,id:data.team.id,name:data.team.name,sector:data.team.sector,generation:data.team.generation,revision:data.team.revision,startedAt:data.team.startedAt,finishedAt:data.team.finishedAt};if(this.pending?.generation!==data.team.generation)this.pending=null;this.paused=false;this.save();this.setStatus('live');this.startPolling();this.onAck(data.team);if(this.pending)this.flush();return data.team;}catch(e){this.setStatus('offline',e.message);throw e;}}
    async resume(){if(!this.connection)return null;this.paused=false;this.setStatus('connecting');try{const data=await this.request('team');this.adopt(data.team);this.startPolling();this.setStatus(this.pending?'syncing':'live');if(this.pending)this.flush();return data.team;}catch(e){this.paused=false;this.startPolling();this.setStatus('offline',e.message);return null;}}
    adopt(team){if(!this.connection)return false;if(team.generation<this.connection.generation||team.generation===this.connection.generation&&team.revision<(this.connection.revision||0))return false;const changed=team.generation!==this.connection.generation;this.connection={...this.connection,generation:team.generation,revision:team.revision,startedAt:team.startedAt,finishedAt:team.finishedAt,name:team.name,sector:team.sector};if(changed){this.pending=null;this.save();this.onReset(team);}else this.save();this.onAck(team);return true;}
    publish(state){if(!this.active())return;this.pending={generation:this.connection.generation,state:clone(state)};this.save();this.setStatus('syncing');clearTimeout(this.flushTimer);this.flushTimer=setTimeout(()=>this.flush(),250);}
    async flush(){if(!this.active()||this.flushing||!this.pending)return;this.flushing=true;const sent=this.pending;try{const data=await this.request('update',{generation:sent.generation,state:sent.state});if(this.pending===sent)this.pending=null;this.adopt(data.team);this.save();this.setStatus(this.pending?'syncing':'live');}catch(e){if(e.data?.team){if(e.data.team.generation!==this.connection.generation)this.adopt(e.data.team);else{this.pending=null;this.save();this.onReset(e.data.team);}this.setStatus('live');}else{this.setStatus('offline',e.message);clearTimeout(this.flushTimer);this.flushTimer=setTimeout(()=>this.flush(),4000);}}finally{this.flushing=false;}if(this.pending&&this.status!=='offline')this.flush();}
    startPolling(){if(this.pollTimer)return;this.pollTimer=setInterval(async()=>{if(!this.active()||this.polling)return;this.polling=true;try{const data=await this.request('team');this.adopt(data.team);this.setStatus(this.pending?'syncing':'live');if(this.pending)this.flush();}catch(e){this.setStatus('offline',e.message);}finally{this.polling=false;}},2500);}
    stop(){this.paused=true;clearInterval(this.pollTimer);this.pollTimer=null;clearTimeout(this.flushTimer);this.setStatus('practice');}
    elapsed(){const c=this.connection;if(!c)return 0;return Math.max(0,(c.finishedAt||Date.now()+this.offset)-c.startedAt);}
    label(){return this.status==='live'?'Live race connected':this.status==='syncing'?'Saving to the race board…':this.status==='connecting'?'Connecting to the race…':this.status==='offline'?'Connection interrupted · progress queued on this device':'Practice · saved on this device';}
  }
  window.NaivashaRace={RaceConnection,facilitator:ORIGIN+'/games/facilitator'};
})();
